{{- range $prom := .Values.alertmanager }}
{{- if $prom.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: {{ $prom.name }}
  name: alertmanager-{{ $prom.name }}
  {{- if ($prom.namespace) }}
  namespace: {{ $prom.namespace }}
  {{- end }}
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    app: alertmanager
    alertmanager: {{ $prom.name }}
  sessionAffinity: ClientIP
  type: ClusterIP
{{- end }}
{{- end }}
