{{- $root := . }}
{{- range $prom := .Values.alertmanager }}
{{- if $prom.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-{{ $prom.name }}
  {{- if ($prom.namespace) }}
  namespace: {{ $prom.namespace }}
  {{- end }}
type: Opaque
data:
  alertmanager.yaml: {{ include $prom.config.scheme.name (set $prom.config "Files" $.Files) | b64enc | quote }}
{{- end }}
{{- end }}
